version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    network_mode: 'host'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'rbmq'
      RABBITMQ_DEFAULT_PASS: 'alberto123'
